"""Initial migration with current models

Revision ID: 7eb9e8acf91f
Revises: 
Create Date: 2025-08-01 17:52:59.067386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb9e8acf91f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profile',
    sa.Column('ProfileID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PhotoURL', sa.Unicode(length=500), nullable=True),
    sa.Column('FirstName', sa.Unicode(length=100), nullable=False),
    sa.Column('LastName', sa.Unicode(length=100), nullable=False),
    sa.Column('Subtitle', sa.Unicode(length=255), nullable=True),
    sa.Column('AddressLine1', sa.Unicode(length=255), nullable=True),
    sa.Column('AddressLine2', sa.Unicode(length=255), nullable=True),
    sa.Column('AddressLine3', sa.Unicode(length=255), nullable=True),
    sa.Column('PhoneNumber', sa.Unicode(length=50), nullable=True),
    sa.Column('EmailAddress', sa.Unicode(length=255), nullable=False),
    sa.Column('Website', sa.Unicode(length=255), nullable=True),
    sa.Column('LinkedInURL', sa.Unicode(length=255), nullable=True),
    sa.Column('GitHubURL', sa.Unicode(length=255), nullable=True),
    sa.Column('OtherSocialProfiles', sa.Unicode(length=500), nullable=True),
    sa.Column('DateOfBirth', sa.Unicode(length=50), nullable=True),
    sa.Column('Nationality', sa.Unicode(length=100), nullable=True),
    sa.Column('CountryCode', sa.Unicode(length=3), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ProfileID'),
    sa.UniqueConstraint('EmailAddress')
    )
    op.create_table('Role',
    sa.Column('RoleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RoleName', sa.Unicode(length=50), nullable=False),
    sa.Column('Description', sa.Unicode(length=255), nullable=True),
    sa.Column('IsSubscription', sa.Boolean(), nullable=True),
    sa.Column('MonthlyCost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('MaxJobApplications', sa.Integer(), nullable=True),
    sa.Column('CanGenerateAIContent', sa.Boolean(), nullable=True),
    sa.Column('CanViewGamification', sa.Boolean(), nullable=True),
    sa.Column('CanManageUsers', sa.Boolean(), nullable=True),
    sa.Column('CanAccessAnalytics', sa.Boolean(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('RoleID'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_table('CoverLetter',
    sa.Column('CoverLetterID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.Unicode(length=255), nullable=False),
    sa.Column('Content', sa.UnicodeText(), nullable=False),
    sa.Column('Format', sa.Unicode(length=50), nullable=True),
    sa.Column('FileURL', sa.Unicode(length=500), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('CoverLetterID')
    )
    op.create_table('Hobbies',
    sa.Column('HobbyID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('HobbyName', sa.Unicode(length=100), nullable=False),
    sa.Column('Description', sa.Unicode(length=500), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('HobbyID')
    )
    op.create_table('JobApplication',
    sa.Column('JobApplicationID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('JobTitle', sa.Unicode(length=255), nullable=False),
    sa.Column('CompanyName', sa.Unicode(length=255), nullable=False),
    sa.Column('Location', sa.Unicode(length=255), nullable=True),
    sa.Column('DateApplied', sa.DateTime(), nullable=False),
    sa.Column('ApplicationStatus', sa.Unicode(length=50), nullable=True),
    sa.Column('Source', sa.Unicode(length=100), nullable=True),
    sa.Column('JobListingURL', sa.Unicode(length=500), nullable=True),
    sa.Column('ResumeVersion', sa.Unicode(length=255), nullable=True),
    sa.Column('CoverLetterVersion', sa.Unicode(length=255), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('JobApplicationID')
    )
    op.create_table('Languages',
    sa.Column('LanguageID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('LanguageName', sa.Unicode(length=100), nullable=False),
    sa.Column('Level', sa.Unicode(length=50), nullable=True),
    sa.Column('Rating', sa.Unicode(length=50), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('LanguageID')
    )
    op.create_table('Objective',
    sa.Column('ObjectiveID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('Objective', sa.Unicode(length=1000), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('ObjectiveID')
    )
    op.create_table('Resume',
    sa.Column('ResumeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.Unicode(length=255), nullable=False),
    sa.Column('Content', sa.UnicodeText(), nullable=False),
    sa.Column('Format', sa.Unicode(length=50), nullable=True),
    sa.Column('FileURL', sa.Unicode(length=500), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('ResumeID')
    )
    op.create_table('Skills',
    sa.Column('SkillID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('SkillName', sa.Unicode(length=100), nullable=False),
    sa.Column('Proficiency', sa.Unicode(length=50), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('SkillID')
    )
    op.create_table('User',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.Unicode(length=100), nullable=False),
    sa.Column('EmailAddress', sa.Unicode(length=255), nullable=False),
    sa.Column('HashedPassword', sa.Unicode(length=500), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('LastLogin', sa.DateTime(), nullable=True),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('Provider', sa.Unicode(length=100), nullable=True),
    sa.Column('ProviderUserID', sa.Unicode(length=100), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['Role.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('EmailAddress'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('UserPreferences',
    sa.Column('PreferenceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('PhotoURLConsent', sa.Boolean(), nullable=True),
    sa.Column('DateOfBirthConsent', sa.Boolean(), nullable=True),
    sa.Column('GitHubURLConsent', sa.Boolean(), nullable=True),
    sa.Column('NationalityConsent', sa.Boolean(), nullable=True),
    sa.Column('OtherSocialProfilesConsent', sa.Boolean(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('PreferenceID')
    )
    op.create_table('AuthLog',
    sa.Column('AuthLogID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('Provider', sa.Unicode(length=50), nullable=False),
    sa.Column('AttemptTime', sa.DateTime(), nullable=False),
    sa.Column('Success', sa.Boolean(), nullable=False),
    sa.Column('ErrorMessage', sa.Unicode(length=500), nullable=True),
    sa.Column('IPAddress', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('AuthLogID')
    )
    op.create_table('JobApplicationAttachment',
    sa.Column('JobApplicationAttachmentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('JobApplicationID', sa.Integer(), nullable=False),
    sa.Column('FileName', sa.Unicode(length=255), nullable=False),
    sa.Column('FileType', sa.Unicode(length=50), nullable=True),
    sa.Column('FileURL', sa.Unicode(length=500), nullable=False),
    sa.Column('uploadedDate', sa.DateTime(), nullable=True),
    sa.Column('uploadedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['JobApplicationID'], ['JobApplication.JobApplicationID'], ),
    sa.PrimaryKeyConstraint('JobApplicationAttachmentID')
    )
    op.create_table('JobApplicationInterview',
    sa.Column('InterviewID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('JobApplicationID', sa.Integer(), nullable=False),
    sa.Column('InterviewDate', sa.DateTime(), nullable=False),
    sa.Column('InterviewType', sa.Unicode(length=50), nullable=True),
    sa.Column('Interviewer', sa.Unicode(length=255), nullable=True),
    sa.Column('InterviewNotes', sa.UnicodeText(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['JobApplicationID'], ['JobApplication.JobApplicationID'], ),
    sa.PrimaryKeyConstraint('InterviewID')
    )
    op.create_table('JobApplicationNote',
    sa.Column('JobApplicationNoteID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('JobApplicationID', sa.Integer(), nullable=False),
    sa.Column('NoteText', sa.UnicodeText(), nullable=False),
    sa.Column('NoteDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['JobApplicationID'], ['JobApplication.JobApplicationID'], ),
    sa.PrimaryKeyConstraint('JobApplicationNoteID')
    )
    op.create_table('JobApplicationStatusHistory',
    sa.Column('StatusHistoryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('JobApplicationID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Unicode(length=50), nullable=False),
    sa.Column('StatusDate', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['JobApplicationID'], ['JobApplication.JobApplicationID'], ),
    sa.PrimaryKeyConstraint('StatusHistoryID')
    )
    op.create_table('JobApplicationTask',
    sa.Column('TaskID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('JobApplicationID', sa.Integer(), nullable=False),
    sa.Column('TaskDescription', sa.Unicode(length=1000), nullable=False),
    sa.Column('TaskStatus', sa.Unicode(length=50), nullable=True),
    sa.Column('DueDate', sa.DateTime(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['JobApplicationID'], ['JobApplication.JobApplicationID'], ),
    sa.PrimaryKeyConstraint('TaskID')
    )
    op.create_table('Message',
    sa.Column('MessageID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('JobApplicationID', sa.Integer(), nullable=True),
    sa.Column('Subject', sa.Unicode(length=255), nullable=True),
    sa.Column('Body', sa.UnicodeText(), nullable=False),
    sa.Column('Format', sa.Unicode(length=50), nullable=True),
    sa.Column('FileURL', sa.Unicode(length=500), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['JobApplicationID'], ['JobApplication.JobApplicationID'], ),
    sa.ForeignKeyConstraint(['ProfileID'], ['Profile.ProfileID'], ),
    sa.PrimaryKeyConstraint('MessageID')
    )
    op.create_table('UserPasswordResetToken',
    sa.Column('UserPasswordResetTokenID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Token', sa.Unicode(length=128), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.Unicode(length=100), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('UserPasswordResetTokenID')
    )
    op.create_index(op.f('ix_UserPasswordResetToken_Token'), 'UserPasswordResetToken', ['Token'], unique=True)
    op.create_table('UserRoleOverride',
    sa.Column('OverrideID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('CapabilityName', sa.Unicode(length=50), nullable=False),
    sa.Column('IsEnabled', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Unicode(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('OverrideID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRoleOverride')
    op.drop_index(op.f('ix_UserPasswordResetToken_Token'), table_name='UserPasswordResetToken')
    op.drop_table('UserPasswordResetToken')
    op.drop_table('Message')
    op.drop_table('JobApplicationTask')
    op.drop_table('JobApplicationStatusHistory')
    op.drop_table('JobApplicationNote')
    op.drop_table('JobApplicationInterview')
    op.drop_table('JobApplicationAttachment')
    op.drop_table('AuthLog')
    op.drop_table('UserPreferences')
    op.drop_table('User')
    op.drop_table('Skills')
    op.drop_table('Resume')
    op.drop_table('Objective')
    op.drop_table('Languages')
    op.drop_table('JobApplication')
    op.drop_table('Hobbies')
    op.drop_table('CoverLetter')
    op.drop_table('Role')
    op.drop_table('Profile')
    # ### end Alembic commands ###
